sonar.projectKey=notes-app
sonar.projectName=NotesApp
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=backend/src/index.js,backend/src/app.js,backend/src/middlewares/multer.middleware.js,frontend/src/**/*